INSERT INTO market (name, event_id) VALUES ('1x2', 1);
INSERT INTO market (name, event_id) VALUES ('1x2', 2);
INSERT INTO market (name, event_id) VALUES ('1x2', 3);
INSERT INTO market (name, event_id) VALUES ('1x2', 4);
INSERT INTO market (name, event_id) VALUES ('1x2', 5);
INSERT INTO market (name, event_id) VALUES ('1x2', 6);
INSERT INTO market (name, event_id) VALUES ('1x2', 7);
INSERT INTO market (name, event_id) VALUES ('1x2', 8);
INSERT INTO market (name, event_id) VALUES ('1x2', 9);
INSERT INTO market (name, event_id) VALUES ('1x2', 10);
INSERT INTO market (name, event_id) VALUES ('1x2', 11);
INSERT INTO market (name, event_id) VALUES ('1x2', 12);
INSERT INTO market (name, event_id) VALUES ('1x2', 13);
INSERT INTO market (name, event_id) VALUES ('1x2', 14);
INSERT INTO market (name, event_id) VALUES ('1x2', 15);
INSERT INTO market (name, event_id) VALUES ('1x2', 16);

INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 1);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 2);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 3);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 4);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 5);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 6);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 7);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 8);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 9);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 10);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 11);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 12);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 13);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 14);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 15);
INSERT INTO market (name, event_id) VALUES ('DOUBLE CHANCE', 16);

INSERT INTO market (name, event_id) VALUES ('HANDICAP', 1);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 2);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 3);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 4);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 5);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 6);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 7);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 8);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 9);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 10);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 11);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 12);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 13);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 14);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 15);
INSERT INTO market (name, event_id) VALUES ('HANDICAP', 16);

INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 1);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 2);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 3);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 4);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 5);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 6);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 7);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 8);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 9);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 10);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 11);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 12);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 13);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 14);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 15);
INSERT INTO market (name, event_id) VALUES ('ODD/EVEN', 16);

INSERT INTO market (name, event_id) VALUES ('YES/NO', 1);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 2);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 3);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 4);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 5);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 6);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 7);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 8);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 9);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 10);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 11);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 12);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 13);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 14);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 15);
INSERT INTO market (name, event_id) VALUES ('YES/NO', 16);