spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/my_first_postgres_database
    username: newuser
    password: password
  liquibase:
    enabled: true
    change-log:
      classpath:db/changelog/changelog.sql
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

