spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/betting-db
    username: newuser
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

