#server:
#  port: 8000 # here we can change the default port
spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files:  sports.sql, competitions.sql, participants.sql, events.sql, events_participants.sql, markets.sql, selections.sql
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  error:
    include-message: always


