spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          import_files:  sql/sports.sql, sql/competitions.sql, sql/participants.sql, sql/events.sql, sql/events_participants.sql, sql/markets.sql, sql/selections.sql
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  error:
    include-message: always


