INSERT INTO participant (name) VALUES ('Arsenal');
INSERT INTO participant (name) VALUES ('Real Madrid');
INSERT INTO participant (name) VALUES ('FC Barcelona');
INSERT INTO participant (name) VALUES ('Manchester United');
INSERT INTO participant (name) VALUES ('Liverpool');
INSERT INTO participant (name) VALUES ('AC Milan');
INSERT INTO participant (name) VALUES ('Juventus');
INSERT INTO participant (name) VALUES ('Borussia Dortmund');
INSERT INTO participant (name) VALUES ('Atletico Bilbao');
INSERT INTO participant (name) VALUES ('FC Shakhtar Donetsk');
INSERT INTO participant (name) VALUES ('Tottenham Hotspur F.C.');
INSERT INTO participant (name) VALUES ('Inter Milan');
INSERT INTO participant (name) VALUES ('Steaua Bucuresti');
INSERT INTO participant (name) VALUES ('FC Bayern Munich');
INSERT INTO participant (name) VALUES ('AS Roma');
INSERT INTO participant (name) VALUES ('Valencia CF');
INSERT INTO participant (name) VALUES ('AFC Ajax');
INSERT INTO participant (name) VALUES ('FC Sevilla');
INSERT INTO participant (name) VALUES ('FC Copenhagen');
INSERT INTO participant (name) VALUES ('FC Zenit St. Petersburg');
INSERT INTO participant (name) VALUES ('Villareal CF');
INSERT INTO participant (name) VALUES ('FC Dinamo Kiyv');
INSERT INTO participant (name) VALUES ('Manchester City FC');
INSERT INTO participant (name) VALUES ('Internazionale');
INSERT INTO participant (name) VALUES ('Everton');
INSERT INTO participant (name) VALUES ('West Ham United');
INSERT INTO participant (name) VALUES ('Leicester City');
INSERT INTO participant (name) VALUES ('Napoli');
INSERT INTO participant (name) VALUES ('Newcastle United');
INSERT INTO participant (name) VALUES ('Lyon');

INSERT INTO participant (name) VALUES ('Senegal');
INSERT INTO participant (name) VALUES ('Netherlands');
INSERT INTO participant (name) VALUES ('Qatar');
INSERT INTO participant (name) VALUES ('Ecuador');
INSERT INTO participant (name) VALUES ('England');
INSERT INTO participant (name) VALUES ('Iran');
INSERT INTO participant (name) VALUES ('USA');
INSERT INTO participant (name) VALUES ('Wales');
INSERT INTO participant (name) VALUES ('Argentina');
INSERT INTO participant (name) VALUES ('Saudi Arabia');
INSERT INTO participant (name) VALUES ('Mexico');
INSERT INTO participant (name) VALUES ('Poland');
INSERT INTO participant (name) VALUES ('Denmark');
INSERT INTO participant (name) VALUES ('Tunisia');
INSERT INTO participant (name) VALUES ('France');
INSERT INTO participant (name) VALUES ('Australia');
INSERT INTO participant (name) VALUES ('Germany');
INSERT INTO participant (name) VALUES ('Japan');
INSERT INTO participant (name) VALUES ('Spain');
INSERT INTO participant (name) VALUES ('Costa Rica');
INSERT INTO participant (name) VALUES ('Morocco');
INSERT INTO participant (name) VALUES ('Croatia');
INSERT INTO participant (name) VALUES ('Belgium');
INSERT INTO participant (name) VALUES ('Canada');
INSERT INTO participant (name) VALUES ('Switzerland');
INSERT INTO participant (name) VALUES ('Cameroon');
INSERT INTO participant (name) VALUES ('Brazil');
INSERT INTO participant (name) VALUES ('Serbia');
INSERT INTO participant (name) VALUES ('Uruguay');
INSERT INTO participant (name) VALUES ('South Korea');
INSERT INTO participant (name) VALUES ('Portugal');
INSERT INTO participant (name) VALUES ('Ghana');